/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package program;

import java.awt.Color;
import java.util.HashSet;
import java.util.Set;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.GroupLayout.Alignment;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.GroupLayout;
import java.awt.Font;
import javax.swing.JLabel;
/**
 *
 * @author oOOo
 */
public class FRT extends javax.swing.JFrame {

    /**
     * Creates new form FRT
     */
    
    private DefaultTableModel tblModel;
    
    public FRT() {
        initComponents();
        initTableModel();
    }
    
    private void initTableModel(){
        String[] columnNames = new String[]{"Mã sách", "Tên sách", "Mã loại sách", "Mã vị trí", "Tình trạng", "Mã tác giả", "Mã nhà xuất bản", "Mã ngôn ngữ", "Số trang", "Năm xuất bản", "Giá sách"};
        tblModel = new DefaultTableModel();
        tblModel.setColumnIdentifiers(columnNames);
     //   tblBooks.setModel(tblModel);
    }
 //   SachDao dao = new SachDao();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnExit = new javax.swing.JButton();
        btnTimkiemtheotheloai = new javax.swing.JButton();
        txtTimkiem = new javax.swing.JTextField();
        btnTimkiemtheoten = new javax.swing.JButton();
        btnTimkiemtheotacgia = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel3.setFont(new Font("Segoe UI", Font.BOLD, 22)); // NOI18N
        jLabel3.setText("Tìm kiếm sách");

        jLabel4.setFont(new Font("Segoe UI", Font.BOLD, 14)); // NOI18N
        jLabel4.setText("Nhập từ khóa");

        btnExit.setText("Thoát");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        btnTimkiemtheotheloai.setText("Tìm kiếm theo thể loại");
        btnTimkiemtheotheloai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimkiemtheotheloaiActionPerformed(evt);
            }
        });

        txtTimkiem.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        btnTimkiemtheoten.setText("Tìm kiếm theo tên");
        btnTimkiemtheoten.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimkiemtheotenActionPerformed(evt);
            }
        });

        btnTimkiemtheotacgia.setText("Tìm kiếm theo tác giả");
        btnTimkiemtheotacgia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimkiemtheotacgiaActionPerformed(evt);
            }
        });

        jTable1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã sách", "Tên sách", "Thể loại", "Tình trạng", "Tác giả", "Nhà xuất bản"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(layout.createSequentialGroup()
        					.addGap(143)
        					.addComponent(jLabel4)
        					.addGap(18)
        					.addComponent(txtTimkiem, GroupLayout.PREFERRED_SIZE, 335, GroupLayout.PREFERRED_SIZE)
        					.addGap(82)
        					.addGroup(layout.createParallelGroup(Alignment.LEADING)
        						.addComponent(btnTimkiemtheotheloai, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        						.addComponent(btnTimkiemtheotacgia, GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
        						.addComponent(btnTimkiemtheoten, Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)))
        				.addComponent(btnExit, Alignment.TRAILING))
        			.addGap(42))
        		.addGroup(layout.createSequentialGroup()
        			.addGap(341)
        			.addComponent(jLabel3)
        			.addContainerGap(366, Short.MAX_VALUE))
        		.addGroup(layout.createSequentialGroup()
        			.addGap(82)
        			.addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 676, GroupLayout.PREFERRED_SIZE)
        			.addContainerGap(96, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addGap(22)
        			.addComponent(jLabel3)
        			.addGap(18)
        			.addComponent(btnTimkiemtheoten)
        			.addGap(18)
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        					.addComponent(txtTimkiem, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        					.addComponent(jLabel4))
        				.addGroup(layout.createSequentialGroup()
        					.addComponent(btnTimkiemtheotacgia)
        					.addGap(18)
        					.addComponent(btnTimkiemtheotheloai)))
        			.addGap(78)
        			.addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 207, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
        			.addComponent(btnExit)
        			.addGap(19))
        );
        getContentPane().setLayout(layout);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
    	view.Tuychon tuychon = new view.Tuychon();
        dispose();
        tuychon.setVisible(true);
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnTimkiemtheotenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimkiemtheotenActionPerformed
        // TODO add your handling code here:
        try{
            String connectionURL = "jdbc:sqlserver://localhost:1433;databaseName=DemoDB";
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            
            Connection con = DriverManager.getConnection(connectionURL);
            
            String sql = "select * from book where title like ?";
            PreparedStatement pstmt = con.prepareStatement(sql);
            
            String searchCriteria = "%";
            if(txtTimkiem.getText().equals("")){
                searchCriteria  += txtTimkiem.getText() + "%";
            }
            pstmt.setString(1, searchCriteria);
            ResultSet rs = pstmt.executeQuery();
            tblModel.setRowCount(0);
            while(rs.next()){
                tblModel.addRow(new Object[]{
                rs.getString("Mã sách"),
                rs.getString("Tên sách"),
                rs.getString("Mã sách"),
                rs.getString("Tên sách"),
                rs.getString("Mã sách"),
                rs.getString("Tên sách"),
                rs.getString("Mã sách"),
                rs.getString("Tên sách"),
                rs.getString("Mã sách"),
                rs.getString("Tên sách"),
                rs.getString("Mã sách"),
                
            });
            }
            tblModel.fireTableDataChanged();
        }
        
        
        catch(Exception e){
            e.printStackTrace();
                JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_btnTimkiemtheotenActionPerformed

    private void btnTimkiemtheotacgiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimkiemtheotacgiaActionPerformed
        // TODO add your handling code here:
        try{
            String connectionURL = "jdbc:sqlserver://localhost:1433;databaseName=DemoDB";
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            
            Connection con = DriverManager.getConnection(connectionURL);
            
            String sql = "select * from book where title like ?";
            PreparedStatement pstmt = con.prepareStatement(sql);
            
            String searchCriteria = "%";
            if(txtTimkiem.getText().equals("")){
                searchCriteria  += txtTimkiem.getText() + "%";
            }
            pstmt.setString(1, searchCriteria);
            ResultSet rs = pstmt.executeQuery();
            tblModel.setRowCount(0);
            while(rs.next()){
                tblModel.addRow(new Object[]{
                rs.getString("Mã sách"),
                rs.getString("Tên sách"),
                rs.getString("Mã sách"),
                rs.getString("Tên sách"),
                rs.getString("Mã sách"),
                rs.getString("Tên sách"),
                rs.getString("Mã sách"),
                rs.getString("Tên sách"),
                rs.getString("Mã sách"),
                rs.getString("Tên sách"),
                rs.getString("Mã sách"),
                
            });
            }
            tblModel.fireTableDataChanged();
        }
        
        
        catch(Exception e){
            e.printStackTrace();
                JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_btnTimkiemtheotacgiaActionPerformed

    private void btnTimkiemtheotheloaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimkiemtheotheloaiActionPerformed
        // TODO add your handling code here:
        try{
            String connectionURL = "jdbc:sqlserver://localhost:1433;databaseName=DemoDB";
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            
            Connection con = DriverManager.getConnection(connectionURL);
            
            String sql = "select * from book where title like ?";
            PreparedStatement pstmt = con.prepareStatement(sql);
            
            String searchCriteria = "%";
            if(txtTimkiem.getText().equals("")){
                searchCriteria  += txtTimkiem.getText() + "%";
            }
            pstmt.setString(1, searchCriteria);
            ResultSet rs = pstmt.executeQuery();
            tblModel.setRowCount(0);
            while(rs.next()){
                tblModel.addRow(new Object[]{
                rs.getString("Mã sách"),
                rs.getString("Tên sách"),
                rs.getString("Mã sách"),
                rs.getString("Tên sách"),
                rs.getString("Mã sách"),
                rs.getString("Tên sách"),
                rs.getString("Mã sách"),
                rs.getString("Tên sách"),
                rs.getString("Mã sách"),
                rs.getString("Tên sách"),
                rs.getString("Mã sách"),
                
            });
            }
            tblModel.fireTableDataChanged();
        }
        
        
        catch(Exception e){
            e.printStackTrace();
                JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_btnTimkiemtheotheloaiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FRT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FRT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FRT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FRT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FRT().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnTimkiemtheotacgia;
    private javax.swing.JButton btnTimkiemtheoten;
    private javax.swing.JButton btnTimkiemtheotheloai;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtTimkiem;
}
