/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package main.java.com.mycompany.kl;
import org.xml.sax.Attributes;
import java.awt.Color;
import java.util.HashSet;
import java.util.Set;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
/**
 *
 * @author oOOo
 */
public class FRT extends javax.swing.JFrame {

    /**
     * Creates new form FRT
     */
    
    private DefaultTableModel tblModel;
    
    public FRT() {
        initComponents();
        initTableModel();
    }
    
    
    private void initTableModel(){
        String[] columnNames = new String[]{"MASACH", "TENSACH", "TENTACGIA", "THELOAI", "SOLUONG", "SOLUONGCONLAI", "SOTRANG", "MAVITRI", "TENNXB"};
        tblModel = new DefaultTableModel();
        tblModel.setColumnIdentifiers(columnNames);
        tbSach.setModel(tblModel);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnExit = new javax.swing.JButton();
        status = new javax.swing.JLabel();
        btnTimkiemtheotheloai = new javax.swing.JButton();
        txtTimkiem = new javax.swing.JTextField();
        btnTimkiemtheoten = new javax.swing.JButton();
        btnTimkiemtheotacgia = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbSach = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Tìm kiếm sách");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(364, 17, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Nhập từ khóa");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(121, 124, -1, -1));

        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        getContentPane().add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(738, 489, -1, -1));

        status.setText("STATUS:");
        getContentPane().add(status, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 492, -1, -1));

        btnTimkiemtheotheloai.setText("Tìm kiếm theo thể loại");
        btnTimkiemtheotheloai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimkiemtheotheloaiActionPerformed(evt);
            }
        });
        getContentPane().add(btnTimkiemtheotheloai, new org.netbeans.lib.awtextra.AbsoluteConstraints(662, 181, -1, -1));

        txtTimkiem.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        getContentPane().add(txtTimkiem, new org.netbeans.lib.awtextra.AbsoluteConstraints(245, 126, 335, -1));

        btnTimkiemtheoten.setText("Tìm kiếm theo tên");
        btnTimkiemtheoten.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimkiemtheotenActionPerformed(evt);
            }
        });
        getContentPane().add(btnTimkiemtheoten, new org.netbeans.lib.awtextra.AbsoluteConstraints(662, 65, 148, -1));

        btnTimkiemtheotacgia.setText("Tìm kiếm theo tác giả");
        btnTimkiemtheotacgia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimkiemtheotacgiaActionPerformed(evt);
            }
        });
        getContentPane().add(btnTimkiemtheotacgia, new org.netbeans.lib.awtextra.AbsoluteConstraints(662, 117, 148, -1));

        tbSach.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tbSach.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "MASACH", "TENSACH", "TENTACGIA", "THELOAI", "SOLUONG", "SOLUONGCONLAI", "SOTRANG", "MAVITRI", "TENNXB"
            }
        ));
        jScrollPane1.setViewportView(tbSach);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 250, 676, 207));

        pack();
    }// </editor-fold>                        

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
        dispose();
    }                                       

    private void btnTimkiemtheotenActionPerformed(java.awt.event.ActionEvent evt) {                                                  
        // TODO add your handling code here:
        try{
            String url = "jdbc:mysql://localhost/quanlysach";
        var user = "root";
        var password = "";
             Connection con = DriverManager.getConnection(url, user, password);
            
            if(txtTimkiem.getText().isEmpty()){
                JOptionPane.showMessageDialog(this, "Ban chua nhap gia tri tim kiem");
            }
            else{
            String sql = "select * from sach where TENSACH like '%"+txtTimkiem.getText()+"%'";
            
            PreparedStatement pstmt = con.prepareStatement(sql);
           
            ResultSet rs = pstmt.executeQuery();
            
          
                tblModel.setRowCount(0);
            while(rs.next()){
                tblModel.addRow(new Object[]{
                rs.getString("MASACH"),
                rs.getString("TENSACH"),
                rs.getString("TENTACGIA"),
                rs.getString("THELOAI"),
                rs.getInt("SOLUONG"),
                rs.getInt("SOLUONGCONLAI"),
                rs.getInt("SOTRANG"),
                rs.getString("MAVITRI"),
                rs.getString("TENNXB"),
                        
            });
            }
            
            
            tblModel.fireTableDataChanged();
            }
        }
        
        
        catch(Exception e){
            e.printStackTrace();
                JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }                                                 

    private void btnTimkiemtheotacgiaActionPerformed(java.awt.event.ActionEvent evt) {                                                     
        // TODO add your handling code here:
        try{
            String url = "jdbc:mysql://localhost/quanlysach";
        var user = "root";
        var password = "";
             Connection con = DriverManager.getConnection(url, user, password);
            
            
            String sql = "select * from sach where TENTACGIA like '%"+txtTimkiem.getText()+"%'";
            
            PreparedStatement pstmt = con.prepareStatement(sql);
           
            ResultSet rs = pstmt.executeQuery();
            
            tblModel.setRowCount(0);
            while(rs.next()){
                tblModel.addRow(new Object[]{
                rs.getString("MASACH"),
                rs.getString("TENSACH"),
                rs.getString("TENTACGIA"),
                rs.getString("THELOAI"),
                rs.getString("SOLUONG"),
                rs.getString("SOLUONGCONLAI"),
                rs.getString("SOTRANG"),
                rs.getString("MAVITRI"),
                rs.getString("TENNXB"),
            });
            }
            tblModel.fireTableDataChanged();
        }
        
        
        catch(Exception e){
            e.printStackTrace();
                JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }                                                    

    private void btnTimkiemtheotheloaiActionPerformed(java.awt.event.ActionEvent evt) {                                                      
        // TODO add your handling code here:
        try{
            String url = "jdbc:mysql://localhost/quanlysach";
        var user = "root";
        var password = "";
             Connection con = DriverManager.getConnection(url, user, password);
            
            if(txtTimkiem != null){
            String sql = "select * from sach where THELOAI like '%"+txtTimkiem.getText()+"%'";
            
            PreparedStatement pstmt = con.prepareStatement(sql);
           
            ResultSet rs = pstmt.executeQuery();
            
            tblModel.setRowCount(0);
            while(rs.next()){
                tblModel.addRow(new Object[]{
                rs.getString("MASACH"),
                rs.getString("TENSACH"),
                rs.getString("TENTACGIA"),
                rs.getString("THELOAI"),
                rs.getString("SOLUONG"),
                rs.getString("SOLUONGCONLAI"),
                rs.getString("SOTRANG"),
                rs.getString("MAVITRI"),
                rs.getString("TENNXB"),
                        
            });
            }
            tblModel.fireTableDataChanged();
        }
            else{
                JOptionPane.showMessageDialog(this, "Ban chua nhap gia tri tim kiem");
            }
        }
        
        
        catch(Exception e){
            e.printStackTrace();
                JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }                                                     

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FRT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FRT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FRT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FRT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FRT().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnTimkiemtheotacgia;
    private javax.swing.JButton btnTimkiemtheoten;
    private javax.swing.JButton btnTimkiemtheotheloai;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel status;
    private javax.swing.JTable tbSach;
    private javax.swing.JTextField txtTimkiem;
    // End of variables declaration                   
}
