/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package main.java.com.mycompany.kl;

import com.mysql.jdbc.Statement;
import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.Set;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.JComponent;


/**
 *
 * @author oOOo
 */
public class ThemSach extends javax.swing.JFrame {
    
    SachDao dao = new SachDao();
    /**
     * Creates new form ThemSach
     */
    public ThemSach() {
        initComponents();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtmasach = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txttensach = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txttentacgia = new javax.swing.JTextField();
        txttheloai = new javax.swing.JTextField();
        txtsotrang = new javax.swing.JTextField();
        txtmavitri = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        btnInsert = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txtsoluong = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtsoluongconlai = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbSach = new javax.swing.JTable();
        status = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txttennxb = new javax.swing.JTextField();
        btndelete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Quản lý sách");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, -1, -1));

        jLabel2.setText("Mã sách");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, -1, -1));
        getContentPane().add(txtmasach, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, 180, -1));

        jLabel3.setText("Tên sách");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, -1));
        getContentPane().add(txttensach, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, 180, -1));

        jLabel4.setText("Tên tác giả");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));

        jLabel5.setText("Thể loại");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, -1, -1));

        jLabel6.setText("Số trang");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 120, -1, -1));

        jLabel7.setText("Mã vị trí");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 160, -1, -1));
        getContentPane().add(txttentacgia, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, 180, -1));
        getContentPane().add(txttheloai, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, 170, -1));
        getContentPane().add(txtsotrang, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 110, 170, -1));

        txtmavitri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmavitriActionPerformed(evt);
            }
        });
        getContentPane().add(txtmavitri, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 150, 170, -1));

        btnSave.setText("Lưu");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        getContentPane().add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 120, -1, -1));

        btnInsert.setText("Thêm mới");
        btnInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertActionPerformed(evt);
            }
        });
        getContentPane().add(btnInsert, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 190, -1, -1));

        btnExit.setText("Thoát");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        getContentPane().add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 370, -1, -1));

        jLabel8.setText("Số lượng");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 40, -1, -1));
        getContentPane().add(txtsoluong, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 30, 170, -1));

        jLabel9.setText("Số lượng còn lại");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 80, -1, -1));
        getContentPane().add(txtsoluongconlai, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 70, 170, -1));

        tbSach.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "masach", "tensach", "tentacgia", "theloai", "soluong", "soluongconlai", "sotrang", "mavitri"
            }
        ));
        jScrollPane1.setViewportView(tbSach);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 650, 130));

        status.setText("STATTUS:");
        getContentPane().add(status, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 200, -1, -1));

        jLabel10.setText("Tên NXB");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, -1, -1));
        getContentPane().add(txttennxb, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, 180, -1));

        btndelete.setText("Xóa");
        btndelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeleteActionPerformed(evt);
            }
        });
        getContentPane().add(btndelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 50, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtmavitriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmavitriActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmavitriActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        StringBuilder sb = new StringBuilder();
        
        if(checkValiDateForm()==true){
            status.setText("Cap nhat thanh cong");
                status.setForeground(Color.red);
        }
        else{
            JOptionPane.showMessageDialog(this, "Ban chua nhap day du gia tri");
        }
        if(sb.length() > 0){
            JOptionPane.showMessageDialog(this, sb);
            return;
        }
        try{
            Sach s = new Sach();
            s.setMASACH(txtmasach.getText());
            s.setTENSACH(txttensach.getText());
            s.setTENTACGIA(txttentacgia.getText());
            s.setTHELOAI(txttheloai.getText());
            s.setTENNXB(txttennxb.getText());
            s.setSOLUONG(txtsoluong.getText());
            s.setSOLUONGCONLAI(txtsoluongconlai.getText());
            s.setSOTRANG(txtsotrang.getText());
            s.setMAVITRI(txtmavitri.getText());
            
            SachDao dao = new SachDao();
            dao.insert(s);
            
            JOptionPane.showMessageDialog(this, "Da luu thanh cong");
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertActionPerformed
        // TODO add your handling code here:
        
        resetForm();
    }//GEN-LAST:event_btnInsertActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnExitActionPerformed

    private void btndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteActionPerformed
        // TODO add your handling code here:
        try{
            String url = "jdbc:mysql://localhost/quanlysach";
        var user = "root";
        var password = "";
             Connection con = DriverManager.getConnection(url, user, password);
            
            String sql = "delete from sach where MASACH = '"+txtmasach.getText()+"'";
            Statement st = (Statement) con.createStatement();
            int chk = JOptionPane.showConfirmDialog(this, "Ban chac chan xoa chu!", "Thong bao!", JOptionPane.YES_NO_OPTION);
            if(chk == JOptionPane.YES_OPTION){
                st.executeUpdate(sql);
                JOptionPane.showMessageDialog(this, "Xoa thanh cong!");
            }
        }catch(Exception e){
            e.printStackTrace();
                JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_btndeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    
    
   
    
    
   
    public void resetForm(){
        txtmasach.setText("");
        txttensach.setText("");
        txttentacgia.setText("");
         txttennxb.setText("");
        txttheloai.setText("");
        txtsoluong.setText("");
        txtsoluongconlai.setText("");
        txtsotrang.setText("");
        txtmavitri.setText("");
    }

public boolean checkValiDateForm(){
        if(txtmasach.getText().isEmpty()||txttensach.getText().isEmpty()||txttentacgia.getText().isEmpty()||txttheloai.getText().isEmpty()
                ||txtsoluong.getText().isEmpty()||txtsoluongconlai.getText().isEmpty()||txtsotrang.getText().isEmpty()||txtmavitri.getText().isEmpty()||txttennxb.getText().isEmpty()){
            return false;
        }
        return true;
    }
    
   
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ThemSach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ThemSach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ThemSach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ThemSach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ThemSach().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnInsert;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btndelete;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel status;
    private javax.swing.JTable tbSach;
    private javax.swing.JTextField txtmasach;
    private javax.swing.JTextField txtmavitri;
    private javax.swing.JTextField txtsoluong;
    private javax.swing.JTextField txtsoluongconlai;
    private javax.swing.JTextField txtsotrang;
    private javax.swing.JTextField txttennxb;
    private javax.swing.JTextField txttensach;
    private javax.swing.JTextField txttentacgia;
    private javax.swing.JTextField txttheloai;
    // End of variables declaration//GEN-END:variables
}
